version: "3"

services:
  app:
    container_name: server
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db"
    expose:
      - 80
    # command: "php artisan migrate"

  db:
    container_name: db
    image: mysql:8.2.0
    expose:
      - 3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=test
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  queue:
    build: .
    depends_on:
      - "app"
    command: "php artisan queue:work -v"

# networks:
#   litghIT
